### ISSUE TITLE
Could you share firestore db structure?

### ISSUE THREAD

**Issue by cameronking4** [diszy10/la-hejo#10]
How is data organized in firestore?

**Comment by diszy10** [comment]
@cameronking4 Data modeling for this currently is structured by root collections.

- Users: Basic user data.
- Products: Product data and current inventory.
- Carts: A one-to-one relationship User to Cart is created by userID === cartID for documents in either collection.

Duct prices may change and should be reflected in the cart. So I would model the cart as below:

```
carts/{userID}
  -- ducts {
      productId: quantity
    }
```

**Comment by cameronking4** [comment]
> @cameronking4 Data modeling for this currently is structured by root collections.
> 
> * Users: Basic user data.
> * Products: Product data and current inventory.
> * Carts: A one-to-one relationship User to Cart is created by userID === cartID for documents in either collection.
> 
> Duct prices may change and should be reflected in the cart. So I would model the cart as below:
> 
> ```
> carts/{userID}
>   -- ducts {
>       productId: quantity
>     }
> ```
